version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
    - ./db:/data/db
    ports:
    - "27017:27017"
  web:
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
     - "3000:3000"
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - ./client:/var/www
     - /var/www/node_modules
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
     - "3333:3333"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/explorer
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - ./server:/var/www
     - /var/www/node_modules