version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    volumes:
      - ./nginx/certs:/certs
    depends_on:
      - mongo
      - web
      - server
    links:
      - mongo
      - web
      - server
    ports:
      - "80:80"
      - "443:443"

  mongo:
    image: mongo:latest
    volumes:
    - ./db/prod:/data/db
    ports:
    - "27017:27017"

  server:
    build:
      context: .
      dockerfile: server-prod.dockerfile
    working_dir: /var/www
    ports:
     - "3333:3333"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/explorer
    links:
     - mongo
    depends_on:
     - mongo

  web:
    build:
      context: .
      dockerfile: client-prod.dockerfile
    working_dir: /var/www
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - server
