FROM node:8-alpine

LABEL maintainer="etienne@tomochain.com"

ENV HOST 0.0.0.0

WORKDIR /app

COPY server .

RUN apk --no-cache --virtual deps add \
      python \
      make \
      g++ \
      bash \
      git \
    && npm install -g \
       npm@latest \
       dotenv \
       node-gyp \
       pm2 \
    && npm install \
    && npm run build \
    && apk del deps

EXPOSE 3333

ENTRYPOINT ["pm2-docker", "start", "pm2.json", "--only", "prod"]
