version: '3'
services:
  mongo:
    image: mongo:3.6
    ports:
     - "27017:27017"
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/explorer
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/tomo-explorer
     - /tomo-explorer/node_modules
     