const { Router } = require('express')
const cors = require('cors')

const AccountController = require('./AccountController')
const TxController = require('./TxController')
const BlockController = require('./BlockController')
const TokenController = require('./TokenController')
const TokenTxController = require('./TokenTxController')
const TokenHolderController = require('./TokenHolderController')
// const AuthController = require('./AuthController')
// const FollowController = require('./FollowController')
const SettingController = require('./SettingController')
const ContractController = require('./ContractController')
const LogController = require('./LogController')
const RewardController = require('./RewardController')
const MixController = require('./MixController')
const MasternodeController = require('./MasternodeController')
const SignMessageController = require('./SignMessageController')
const HomeController = require('./HomeController')
const EpochController = require('./EpochController')

const router = Router()

// Add USERS Routes
router.all('*', cors())
// router.use(AuthController)
router.use(BlockController)
router.use(AccountController)
router.use(TxController)
router.use(TokenController)
router.use(TokenTxController)
router.use(TokenHolderController)
// router.use(FollowController)
router.use(SettingController)
router.use(ContractController)
router.use(LogController)
router.use(RewardController)
router.use(MixController)
router.use(MasternodeController)
router.use(SignMessageController)
router.use(HomeController)
router.use(EpochController)

module.exports = router
