swagger: '2.0'
info:
  version: 1.0.0
  title: TomoScan APIs
  description: TomoScan APIs
  license:
    name: Github
    url: 'https://github.com/tomochain/tomoscan'
tags:
  - name: Accounts
    description: Accounts API
  - name: Blocks
    description: Blocks API
  - name: Transactions
    description: Transactions API
  - name: Tokens
    description: Tokens API

consumes:
  - application/json
produces:
  - application/json
paths:
  /api/accounts:
    get:
      tags:
        - Accounts
      summary: Get list accounts
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/accounts/{hash}:
    get:
      tags:
        - Accounts
      summary: Get account detail
      parameters:
        - name: hash
          in: path
          required: true
          description: account address
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
  /api/accounts/{hash}/mined:
    get:
      tags:
        - Accounts
      summary: Get list block create
      parameters:
        - name: hash
          in: path
          required: true
          description: account address
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error

  /api/blocks:
    get:
      tags:
        - Blocks
      summary: Get list blocks
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/blocks/{hash}:
    get:
      tags:
        - Blocks
      summary: Get block detail
      parameters:
        - name: hash
          in: path
          required: true
          description: block number or block hash
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
  /api/blocks/{blockNumber}/address/{address}:
    get:
      tags:
        - Blocks
      summary: Check exist transaction from/to address inside block
      parameters:
        - name: blockNumber
          in: path
          required: true
          description: block number
          type: number
        - name: address
          in: path
          required: true
          description: address
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
  /api/blocks/signers/{blockNumber}:
    get:
      tags:
        - Blocks
      summary: Get list signers of a block
      parameters:
        - name: blockNumber
          in: path
          required: true
          description: account address
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error

  /api/txs:
    get:
      tags:
        - Transactions
      summary: Get list blocks. Params limit & page & ((address & tx_account) | block | type)
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
        - name: address
          in: query
          required: false
          description: list tx of address, group with tx_account
          type: string
        - name: tx_account
          in: query
          required: false
          description: in|out, default = all, group with address
          type: string
        - name: block
          in: query
          required: false
          description: list tx of a block
          type: number
        - name: type
          in: query
          required: false
          description: signTxs|otherTxs|pending|all
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/txs/listByType/{type}:
    get:
      tags:
        - Transactions
      summary: Get list txs by type.
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 100
          type: number
        - name: type
          in: path
          required: true
          description: signTxs|otherTxs|pending|all
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/txs/listByBlock/{blockNumber}:
    get:
      tags:
        - Transactions
      summary: Get list txs by block number.
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 100
          type: number
        - name: blockNumber
          in: path
          required: true
          description: block number
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/txs/listByAccount/{address}:
    get:
      tags:
        - Transactions
      summary: Get list txs by account address.
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 100
          type: number
        - name: address
          in: path
          required: true
          description: account address
          type: string
        - name: filterAddress
          in: query
          required: false
          description: optional
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/txs/{hash}:
    get:
      tags:
        - Transactions
      summary: Get transaction detail
      parameters:
        - name: hash
          in: path
          required: true
          description: transaction hash
          type: string
      responses:
        200:
          description: OK
        404:
          description: Not Found
        500:
          description: Server Internal Error

  /api/tokens:
    get:
      tags:
        - Token
      summary: Get list tokens
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/tokens/{hash}:
    get:
      tags:
        - Tokens
      summary: Get token detail
      parameters:
        - name: hash
          in: path
          required: true
          description: token address
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
  /api/tokens/{token}/holder/{holder}:
    get:
      tags:
        - Tokens
      summary: Get token holder detail
      parameters:
        - name: token
          in: path
          required: true
          description: token address
          type: string
        - name: holder
          in: path
          required: true
          description: holder address
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
  /api/token-txs:
    get:
      tags:
        - Accounts
      summary: Get list token transactions. Require 1 of 2 conditions - address | token
      parameters:
        - name: address
          in: query
          required: false
          description: account address
          type: string
        - name: token
          in: path
          required: false
          description: token address
          type: string
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/token-holders:
    get:
      tags:
        - Accounts
      summary: Get list token holder. Require 1 of 2 conditions - address | hassh
      parameters:
        - name: address
          in: query
          required: false
          description: token address
          type: string
        - name: hash
          in: query
          required: false
          description: account address
          type: string
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error


  /api/rewards/{voter}:
    get:
      tags:
        - Rewards
      summary: Get list rewards of a voter
      parameters:
        - name: voter
          in: path
          required: true
          description: account address
          type: number
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        500:
          description: Server Internal Error
  /api/rewards/epoch/{epochNumber}:
    get:
      tags:
        - Rewards
      summary: Get list reward of an epoch
      parameters:
        - name: epochNumber
          in: path
          required: true
          description: epoch number
          type: number
        - name: hash
          in: path
          required: true
          description: account address
          type: string
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
  /api/epochs:
    get:
      tags:
        - Epoch
      summary: Get list epoch
      parameters:
        - name: page
          in: query
          required: false
          description: default = 1
          type: number
        - name: limit
          in: query
          required: false
          description: default 20, maximum = 50
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
  /api/epochs/{epochNumber}:
    get:
      tags:
        - Epoch
      summary: Get epoch detail
      parameters:
        - name: epochNumber
          in: path
          required: true
          description: epoch number
          type: number
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found
        500:
          description: Server Internal Error
